-- Run in Supabase SQL Editor to add the Competitions section.
-- Safe to re-run thanks to IF NOT EXISTS / ON CONFLICT.

-- ============ TABLE ============
create table if not exists competitions (
  id          bigint generated by default as identity primary key,
  title       text not null,
  event       text,
  role        text,
  date        text,
  location    text,
  placement   text,
  description text,
  link_url    text,
  skills      text[] not null default '{}',
  image_urls  text[] not null default '{}',
  visible     boolean not null default true,
  order_index integer not null default 0,
  created_at  timestamp with time zone not null default now()
);

-- ============ RLS ============
alter table competitions enable row level security;

drop policy if exists "competitions_read" on competitions;
create policy "competitions_read"
  on competitions for select
  using (true);

drop policy if exists "competitions_write" on competitions;
create policy "competitions_write"
  on competitions for all
  to authenticated
  using (true)
  with check (true);

-- ============ SECTION ROW ============
-- Append the section to the end of the homepage list. Adjust order_index later
-- via the Sections admin tab to put it where you want.
insert into sections (key, title, visible, order_index)
values ('competitions', 'Competitions', true, coalesce((select max(order_index) from sections), -1) + 1)
on conflict (key) do nothing;
